# Copyright 2020 DGT NETWORK INC © Stanislav Parsov
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f families/settings/Dockerfile -t settings-tp.

FROM ubuntu:jammy
ARG DGT_TOP
RUN apt-get update \
 && apt-get install gnupg -y


RUN apt-get update \
    && apt-get install -y -q  \
    git \
    python3 \
    python3-stdeb python3-pip python-is-python3

RUN apt-get install -y -q --allow-downgrades \
    python3-grpcio \
    python3-protobuf

RUN apt-get install -y -q --allow-downgrades \
    python3-colorlog \
    python3-toml \
    python3-yaml \
    python3-zmq  \
    python3-cbor  \
    python3-cryptography>=1.7.1



RUN pip3 install grpcio-tools
#RUN pip3 install pyformance
#RUN pip3 install chardet
RUN pip3 install secp256k1
RUN pip3 install pysha3



ENV PATH=$PATH:/project/$DGT_TOP/bin:/protoc3/bin

WORKDIR /project/$DGT_TOP

CMD echo "\033[0;32m--- Building settings ---\n\033[0m" \
 && bin/protogen \
 && cd families/settings \
 && python3 setup.py clean --all \
 && python3 setup.py build
