# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f sdk/examples/intkey_python/Dockerfile -t intkey-tp-python-local .

# -------------=== intkey-tp-python build ===-------------

FROM ubuntu:jammy
ARG DGT_TOP
RUN apt-get update \
 && apt-get install gnupg -y

RUN apt-get update && apt-get install -y -q \
    git \
    python3 \
    python3-stdeb python3-pip

RUN apt-get install -y -q \
    python3-grpcio \
    python3-protobuf

RUN apt-get install -y -q \
    python3-cbor \
    python3-colorlog \
    python3-toml \
    python3-yaml \
    python3-zmq  \
    python3-cryptography>-1.7.1 \
    python3-lmdb      \
    python3-protobuf

RUN pip3 install grpcio-tools 
RUN pip3 install secp256k1
RUN pip3 install pysha3
RUN mkdir -p /var/log/dgt

ENV PATH=$PATH:/project/$DGT_TOP/bin:/project/$DGT_TOP/bgx/bin

WORKDIR /project/$DGT_TOP

CMD echo "\033[0;32m--- Building pbft_python ---\n\033[0m" \
 && bin/protogen \
 && cd consensus/pbft_python \
 && python3 setup.py clean --all \
 && python3 setup.py build
