# Copyright 2023 DGT NETWORK INC © Stanislav Parsov
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f rest_api/Dockerfile -t sawtooth-rest-api-local .

# -------------=== rest_api build ===-------------

FROM ubuntu:jammy
ARG DGT_TOP

# git python3-stdeb net-tools pkg-config
RUN apt-get update && apt-get install --no-install-recommends -y -q \
    iputils-ping \
    unzip         \
    openssl

RUN apt-get install --no-install-recommends -y -q \
    python3       \
    python3-pip   \
    python3-grpcio \
    python3-protobuf 
    

RUN apt-get install --no-install-recommends -y -q \
    python3-cbor \
    python3-colorlog \
    python3-cryptography>=1.7.1 \
    python3-dev \
    python3-lmdb \
    python3-netifaces \
    python3-toml \
    python3-yaml \
    python3-zmq \
    python3-requests \
    python3-sha3 \
    && rm -rf /var/lib/apt/lists/*
     
      
#  python3-graphviz libssl-dev
RUN pip3 install secp256k1
RUN pip3 install grpcio-tools
RUN pip3 install pyformance
RUN pip3 install chardet
RUN pip3 install aiodns aiohttp aiohttp_security[session] oauthlib
RUN pip3  install pytelegrambotapi
#RUN pip3 install dialogflow
RUN pip3 install google-cloud-dialogflow
#RUN pip3 install pysocks
RUN pip3 install hvac   "hvac[parser]"          
				  
RUN mkdir /var/log/dgt

ENV PATH=$PATH:/project/$DGT_TOP/bin:
ENV GOOGLE_APPLICATION_CREDENTIALS=./small-talk.json
ENV LANG=ru_RU.UTF-8
WORKDIR /project/$DGT_TOP

CMD echo "\033[0;32m--- Building dgt_bot_api ---\n\033[0m" \
 && bin/protogen \
 && cd telebot \
 && python3 setup.py clean --all \
 && python3 setup.py build
