# Copyright 2020 NTRLab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f rest_api/Dockerfile -t sawtooth-rest-api-local .

# -------------=== rest_api build ===-------------

FROM ubuntu:bionic
ARG DGT_TOP
RUN apt-get update \
 && apt-get install gnupg -y

RUN echo "deb http://repo.sawtooth.me/ubuntu/ci bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8AA7AF1F1091A5FD \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 8AA7AF1F1091A5FD) \
 && apt-get update

RUN apt-get update && apt-get install -y -q \
    git \
    python3 \
    python3-stdeb \
    python3-pip   \
    language-pack-ru \
    python3-lmdb

RUN apt-get install -y -q \
    python3-grpcio \
    python3-grpcio-tools \
    python3-protobuf

RUN apt-get install -y -q \
    python3-aiodns \
    python3-aiohttp \
    python3-colorlog \
    python3-cchardet\
    python3-pyformance \
    python3-toml \
    python3-yaml \
    python3-zmq  \
    python3-secp256k1 python3-cryptography>=1.7.1 \
    python3-cbor

RUN pip3  install pytelegrambotapi
#RUN pip3 install dialogflow
RUN pip3 install google-cloud-dialogflow
RUN pip3 install pysocks
RUN pip3 install hvac             
RUN pip3 install "hvac[parser]"
RUN pip3 install pysha3  
				  
RUN mkdir /var/log/dgt

ENV PATH=$PATH:/project/$DGT_TOP/bin:/project/$DGT_TOP/bgx/bin
ENV GOOGLE_APPLICATION_CREDENTIALS=./small-talk.json
ENV LANG=ru_RU.UTF-8
WORKDIR /project/$DGT_TOP

CMD echo "\033[0;32m--- Building dgt_bot_api ---\n\033[0m" \
 && bin/protogen \
 && cd telebot \
 && python3 setup.py clean --all \
 && python3 setup.py build
