# Copyright 2023 DGT NETWORK INC © Stanislav Parsov
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -------------===  build ===-------------

FROM ubuntu:jammy
ARG DGT_TOP

# git python3-stdeb net-tools pkg-config
RUN apt-get update && apt-get install --no-install-recommends -y -q \
    iputils-ping \
    unzip         \
    openssl

RUN apt-get install --no-install-recommends -y -q \
    python3       \
    python3-pip   \
    python3-grpcio \
    python3-protobuf 
    
# jq
RUN apt-get install --no-install-recommends -y -q \
    python3-cbor \
    python3-colorlog \
    python3-cryptography>=1.7.1 \
    python3-dev \
    python3-lmdb \
    python3-netifaces \
    python3-toml \
    python3-yaml \
    python3-zmq \
    python3-requests \
    python3-sha3 \
    && rm -rf /var/lib/apt/lists/*
     
      
#  python3-graphviz libssl-dev
RUN pip3 install secp256k1
RUN pip3 install grpcio-tools
RUN pip3 install pyformance
RUN pip3 install chardet
RUN pip3 install aiodns aiohttp aiohttp_security[session] oauthlib
RUN pip3 install hvac "hvac[parser]"            
#RUN pip3 install "hvac[parser]"

 
COPY ./docker/vault/vault_1.10.2_linux_amd64.zip /usr/local/bin
RUN (cd /usr/local/bin;unzip   vault_1.10.2_linux_amd64.zip)   

RUN ln -s /usr/bin/python3 /usr/bin/python
ENV PATH=$PATH:/project/$DGT_TOP/bin
WORKDIR /project/$DGT_TOP

CMD echo "\033[0;32m--- Building vault ---\n\033[0m" 

 
