# Copyright 2020 DGT NETWORK INC © Stanislav Parsov
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -------------===  build ===-------------

FROM ubuntu:bionic
ARG DGT_TOP
RUN apt-get update \
 && apt-get install gnupg -y


RUN echo "deb http://repo.sawtooth.me/ubuntu/ci bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8AA7AF1F1091A5FD \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 8AA7AF1F1091A5FD) \
 && apt-get update

RUN apt-get update && apt-get install -y -q \
    git \
    iputils-ping\
    net-tools\
    python3 \
    python3-stdeb python3-pip

RUN apt-get install -y -q \
    python3-grpcio \
    python3-grpcio-tools \
    python3-protobuf

RUN apt-get install -y -q \
    pkg-config \
    python3-colorlog \
    python3-toml \
    python3-yaml \
    unzip jq \
    python3-zmq python3-cbor python3-secp256k1 python3-cryptography>=1.7.1
 
RUN pip3 install hvac             
RUN pip3 install "hvac[parser]"
RUN pip3 install pysha3
 
COPY ./docker/vault/vault_1.10.2_linux_amd64.zip /usr/local/bin
RUN (cd /usr/local/bin;unzip   vault_1.10.2_linux_amd64.zip)   

#RUN apt-get update && apt-get install -y lsb-release && apt-get clean all      
# (cd /usr/local/bin/; unzip /project/dgt/docker/vault/vault_1.10.0_linux_amd64.zip)
#RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
#RUN pwd;ls -l 
#RUN apt-key add /project/$DGT_TOP/docker/vault/gpg
#RUN apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
#RUN apt-get update && sudo apt-get install vault


RUN ln -s /usr/bin/python3 /usr/bin/python
ENV PATH=$PATH:/project/$DGT_TOP/bin
WORKDIR /project/$DGT_TOP

CMD echo "\033[0;32m--- Building vault ---\n\033[0m" 

 
