# Copyright 2020 DGT NETWORK INC © Stanislav Parsov
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f validator/Dockerfile -t validator-dgt .

# -------------===  build ===-------------

FROM ubuntu:jammy
ARG DGT_TOP
RUN apt-get update \
 && apt-get install gnupg -y

RUN apt-get update && apt-get install -y -q \
    git \
    iputils-ping\
    net-tools unzip \
    python3 \
    python3-stdeb python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get install -y -q \
    python3-grpcio \
    python3-protobuf \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get install -y -q \
    libssl-dev \
    openssl \
    pkg-config \
    python3-cbor \
    python3-colorlog \
    python3-cryptography>=1.7.1 \
    python3-dev \
    python3-lmdb \
    python3-netifaces \
    python3-toml \
    python3-yaml \
    python3-zmq \
    && rm -rf /var/lib/apt/lists/*
     
      
#  python3-graphviz
RUN pip3 install secp256k1
RUN pip3 install grpcio-tools
RUN pip3 install pyformance
RUN pip3 install chardet
RUN pip3 install aiodns
RUN pip3 install aiohttp
RUN pip3 install aiohttp_security[session]


RUN pip3 install pysha3

ENV PATH=$PATH:/project/$DGT_TOP/bin:/protoc3/bin

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN mkdir -p /etc/dgt/keys
RUN mkdir -p /var/lib/dgt
RUN mkdir -p /var/log/dgt

#ENV PATH=$PATH:/project/$DGT_TOP/bin

WORKDIR /project/$DGT_TOP

CMD echo "\033[0;32m--- Building common ---\n\033[0m" \
 && bin/protogen \
 && cd validator \
 && if [ -d "debian" ]; then rm -rf debian; fi \
 && python3 setup.py clean --all \
 && python3 setup.py --command-packages=stdeb.command debianize \
 && if [ -d "packaging/ubuntu" ]; then cp -R packaging/ubuntu/* debian/; fi 
 
