{
 "title": "DGT-NET",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Chain Head",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.chain.ChainController.chain_head",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "blocks" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.chain.ChainController.block_num",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "graph",
   "description": "The current count of transactions committed to the blockstore. Note that on forking networks, this is not necessarily monotonic.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "transactions" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.chain.ChainController.committed_transactions_gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocks Published",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "blocks" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.publisher.BlockPublisher.blocks_published_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocks Considered",
   "type": "graph",
   "description": "The number of blocks that go through the validation process",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "blocks" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.chain.ChainController.blocks_considered_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chain Head Moved To Fork",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "fork changes" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.chain.BlockValidator.chain_head_moved_to_fork_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pending Batches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "batches" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.publisher.BlockPublisher.pending_batch_gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batches Rejected (Backpressure)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "batches" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.back_pressure_handlers.ClientBatchSubmitBackpressureHandler.backpressure_batches_rejected_gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Execution Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.executor.TransactionExecutorThread.transaction_execution_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions in Process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "transactions" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.executor.TransactionExecutorThread.in_process_transactions_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Processing Duration (99th Percentile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.interconnect.Interconnect.send_response_time",
     "select": [
      [
       { "params": [ "99_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "message_type", "operator": "=", "value": "TP_PROCESS_REQUEST" }
     ]
    }
   ]
  },
  {
   "title": "REST API Validator Response Time (75th Percentile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_rest_api.post_batches_validator_time",
     "select": [
      [
       { "params": [ "75_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rest API Batch Submission Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "batches per second" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_rest_api.post_batches_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "dgt_rest_api.post_batches_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Valid Transaction Response Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.executor.TransactionExecutorThread.tp_process_response_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "response_type", "operator": "=", "value": "OK" }
     ]
    }
   ]
  },
  {
   "title": "Invalid Transaction Response Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.executor.TransactionExecutorThread.tp_process_response_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "response_type", "operator": "=", "value": "INVALID_TRANSACTION" }
     ]
    }
   ]
  },
  {
   "title": "Internal Error Response Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.executor.TransactionExecutorThread.tp_process_response_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "response_type", "operator": "=", "value": "INTERNAL_ERROR" }
     ]
    }
   ]
  },
  {
   "title": "Message Round Trip Times 95th Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]] [[tag_message_type]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "message_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.interconnect.Interconnect.send_response_time",
     "select": [
      [
       { "params": [ "95_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Messages Sent Per Second by Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "messages per second" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]] [[tag_message_type]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "message_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.interconnect.Interconnect.send_response_time",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Message Receive Rate by Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "messages per second" }
   ],
   "targets": [
    {
     "alias": "received messages [[tag_host]] [[tag_message_type]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "message_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.interconnect._SendReceive.received_message_count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packets Per Second (+Recv/-Sent)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "packets per second" }
   ],
   "targets": [
    {
     "alias": "Packets Received [[tag_host]] [[tag_interface]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Packets Sent [[tag_host]] [[tag_interface]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Per Second (+Recv/-Sent)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes per second" }
   ],
   "targets": [
    {
     "alias": "bytes recv [[tag_host]] [[tag_interface]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "bytes sent [[tag_host]] [[tag_interface]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU per Process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "user cpu [[tag_host]] [[tag_process_name]]-[[tag_pid]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_time_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "system cpu [[tag_host]] [[tag_process_name]]-[[tag_pid]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_time_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "user [[tag_host]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "system [[tag_host]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "write_bytes [[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "read_bytes [[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "IO Wait",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "memory used [[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "context switches [[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resident Memory by Process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Threadpool Task Run Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.threadpool.InstrumentedThreadPoolExecutor.task_run_time",
     "query": "SELECT last(\"99_percentile\") FROM \"dgt_validator.Component-threadpool.task_run_time\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "99_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Network" }
     ]
    }
   ]
  },
  {
   "title": "Network Threadpool Task Time in Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 105 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.threadpool.InstrumentedThreadPoolExecutor.task_time_in_queue",
     "select": [
      [
       { "params": [ "99_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Network" }
     ]
    }
   ]
  },
  {
   "title": "Network Threadpool Workers in Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 105 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.threadpool.InstrumentedThreadPoolExecutor.workers_in_use",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Network" }
     ]
    }
   ]
  },
  {
   "title": "Component Threadpool Task Run Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.threadpool.InstrumentedThreadPoolExecutor.task_run_time",
     "select": [
      [
       { "params": [ "99_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Component" }
     ]
    }
   ]
  },
  {
   "title": "Component Threadpool Task Time in Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.threadpool.InstrumentedThreadPoolExecutor.task_time_in_queue",
     "select": [
      [
       { "params": [ "99_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Component" }
     ]
    }
   ]
  },
  {
   "title": "Component Threadpool Workers in Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.threadpool.InstrumentedThreadPoolExecutor.workers_in_use",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Component" }
     ]
    }
   ]
  },
  {
   "title": "Signature Threadpool Task Run Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.threadpool.InstrumentedThreadPoolExecutor.task_run_time",
     "query": "SELECT last(\"99_percentile\") FROM \"dgt_validator.threadpool.InstrumentedThreadPoolExecutor.task_run_time\" WHERE (\"name\" = 'Signature') AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "99_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Signature" }
     ]
    }
   ]
  },
  {
   "title": "Signature Threadpool Task Time in Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 119 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.threadpool.InstrumentedThreadPoolExecutor.task_time_in_queue",
     "query": "SELECT last(\"99_percentile\") FROM \"dgt_validator.threadpool.InstrumentedThreadPoolExecutor.task_time_in_queue\" WHERE (\"name\" = 'Signature') AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "99_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Signature" }
     ]
    }
   ]
  },
  {
   "title": "Signature Threadpool Workers in Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.threadpool.InstrumentedThreadPoolExecutor.workers_in_use",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Signature" }
     ]
    }
   ]
  },
  {
   "title": "Executing Threadpool Task Run Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"99_percentile\") FROM \"dgt_validator.threadpool.InstrumentedThreadPoolExecutor.task_run_time\" WHERE (\"name\" = 'Executing') AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executing Threadpool Task Run Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"99_percentile\") FROM \"dgt_validator.threadpool.InstrumentedThreadPoolExecutor.task_time_in_queue\" WHERE (\"name\" = 'Executing') AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executing Threadpool Workers in Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"count\") FROM \"dgt_validator.threadpool.InstrumentedThreadPoolExecutor.workers_in_use\" WHERE (\"name\" = 'Executing') AND $timeFilter GROUP BY time($__interval), \"host\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dispatcher Server Thread Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.interconnect._SendReceive.dispatcher_queue_size",
     "query": "SELECT mean(\"value\") FROM \"dgt_validator.interconnect.dispatcher_queue_size\" WHERE (\"connection\" = 'OutBoundCOnnectionTHread') AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "connection", "operator": "=", "value": "ServerThread" }
     ]
    }
   ]
  },
  {
   "title": "Dispatcher Outbound Connection Thread Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dgt_validator.interconnect._SendReceive.dispatcher_queue_size",
     "query": "SELECT mean(\"value\") FROM \"dgt_validator.interconnect.dispatcher_queue_size\" WHERE (\"connection\" =~ 'OutboundConnectionThread') AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "connection", "operator": "=~", "value": "/OutboundConnectionThread/" }
     ]
    }
   ]
  }
 ]
}