# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stuff_common/protobuf/smart_stuff_token.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stuff_common/protobuf/smart_stuff_token.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\030sawtooth.config.protobufP\001'),
  serialized_pb=_b('\n-stuff_common/protobuf/smart_stuff_token.proto\"b\n\x0eStuffTokenInfo\x12\x12\n\ngroup_code\x18\x01 \x01(\t\x12\x11\n\towner_key\x18\x02 \x01(\t\x12\x0c\n\x04sign\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t\x12\r\n\x05stuff\x18\x05 \x01(\x0c\x42\x1c\n\x18sawtooth.config.protobufP\x01\x62\x06proto3')
)




_STUFFTOKENINFO = _descriptor.Descriptor(
  name='StuffTokenInfo',
  full_name='StuffTokenInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_code', full_name='StuffTokenInfo.group_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_key', full_name='StuffTokenInfo.owner_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sign', full_name='StuffTokenInfo.sign', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='StuffTokenInfo.user', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stuff', full_name='StuffTokenInfo.stuff', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['StuffTokenInfo'] = _STUFFTOKENINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StuffTokenInfo = _reflection.GeneratedProtocolMessageType('StuffTokenInfo', (_message.Message,), dict(
  DESCRIPTOR = _STUFFTOKENINFO,
  __module__ = 'stuff_common.protobuf.smart_stuff_token_pb2'
  # @@protoc_insertion_point(class_scope:StuffTokenInfo)
  ))
_sym_db.RegisterMessage(StuffTokenInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
