# Copyright 2020 NTRLab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -------------===  build ===-------------

FROM ubuntu:jammy
ARG DGT_TOP
RUN apt-get update \
 && apt-get install gnupg -y

RUN apt-get update && apt-get install -y -q \
    git \
    iputils-ping net-tools\
    python3 \
    python3-stdeb

RUN apt-get install -y -q \
    python3-grpcio \
    python3-protobuf

RUN apt-get install -y -q \
    python3-cbor \
    python3-colorlog \
    python3-cryptography>=1.7.1 \
    python3-toml \
    python3-yaml python3-pip

RUN pip3 install secp256k1
RUN pip3 install grpcio-tools
RUN pip3 install cryptography
RUN pip3 install pysha3

# take Ethereum hash function
# import sha3
# k = sha3.keccak_256()
# k.update('age'.encode())
# print (k.hexdigest())
# addr = keccak_256('51fe1dfe5211f93bc7'.encode()).digest()[-20:].hex()
#RUN pip3 install pysha3

ENV PATH=$PATH:/project/$DGT_TOP/bin:/project/$DGT_TOP/bgx/bin

WORKDIR /project/$DGT_TOP
